plugins:
  - prettier
parserOptions:
  ecmaVersion: 2017
extends:
  - prettier
rules:
  # prettier
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false
  # rules
  prefer-const: 2
  no-unused-vars:
    - 2
    - argsIgnorePattern: ^_
  no-multiple-empty-lines:
    - 2
    - max: 1
  no-var: 2
